# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content_media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'bmp', 'gif', 'avi', 'mpeg', 'mp4'])]),
        ),
    ]
