# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tweet_content_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'bmp', 'gif', 'avi', 'mpeg', 'mp4'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content_media',
        ),
        migrations.AddField(
            model_name='tweetmedia',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
    ]
