# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20180826_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetmedia',
            old_name='media',
            new_name='media_file',
        ),
    ]
