# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20180905_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'bmp', 'gif', 'avi', 'mpeg', 'mp4', 'jpg'])]),
        ),
    ]
